### ISSUE TITLE
Refactor GridAPPS-D specific translators in Message Contenting Service to TsService

### ISSUE THREAD

**Issue by ericstephan** [pnnl/proven-cluster#63]
Performing the translation on the routing service creates the potential for bottlenecks.  The raw gridappsd. message will be bundled as a part of the knowledge message where it is translated into the general form and then ingested into the Influx store.

**Comment by ericstephan** [comment]
@telsethag @bibiraju - should I create utility class for the GridAPPS-D specific message conversions and put it in gov.pnnl.cluster.lib.pipeline.gridappsd ?

**Comment by telsethag** [comment]
@ericstephan @bibiraju - yes, moving it to the pipeline library sounds good.

**Comment by ericstephan** [comment]
This initial task was superseded by the Refactor TsService Epic.
